const language = {
    loadevent: "事件讀取中...",
    loadcmd: "指令讀取中...",
    ready: "連線成功！",
    loadslash: "成功載入機器人 [/] 指令",
    error1: "機器人 token 錯誤或是未開啟 INTENTS 權限",
    error2: "請在 token.js 設定機器人 token。",
    loadclientevent: "客戶端事件讀取中...",
    Loaded_command: "指令讀取",
    Loaded_command_fal: "指令未讀取",
    Loaded_command_fal_msg:"原因:控制項關閉",
    message3: "權限不足。",
    error3: "重新載入機器人 [/] 指令時發生錯誤：",
    error4: "警告：看起來您沒有填人 Mongodb 網址？如果您在 config.js 裡沒有填人有效的 Mongodb 網址，您沒辦法使用機器人。",
    error5: "",
    msg32: "是時候該建立自己的機器人了，快到 https://github.com/Tdr-gaming-studio/gitaenobot/tree/v2 設定自己的機器人吧！，我是開源的歐!!!",
    msg33: "指令",
    msg34: "您已經輸入過這個指令了。 ❌",
    msg49: `訊息 Ping`,
    msg50: `訊息延遲`,
    msg51: `API 延遲`,
    msg86: "更新",
    msg120: "請指定一個文字頻道。",
    msg121: "<#{channel}> 已經被設為指令頻道，現在在其他頻道是無效的。",
    msg122: "目前沒有註冊的資料。",
    msg123: "<#{channel}> 被移除自指令頻道。",
    msg124: "這個頻道已經是指令頻道了。",
    msg125: "這裡似乎不是一個文字頻道。",
    msg127: "指令未被定義。",
   }
   module.exports = language;